# sesame -- POSIX make. No external build system; zlib is the only dependency.
#
#   make            build sesame
#   make asan       build with ASan/UBSan
#   make test       run the golden tests (needs an R with sesame; override the
#                   binary with RSCRIPT=, e.g. make test RSCRIPT=Rscript-4.6.0).
#                   The targets are independent and each driver works in its
#                   own mktemp dir, so `make -j8 test` runs them in parallel
#                   (221 s on 8 cores vs ~35 min serial with the R oracle,
#                   and -j16 is no faster: the longest single target sets it;
#                   add -Otarget under GNU make to keep each target's output
#                   together).
#   make test-docs  run every documented example against the built binary
#                   (needs the store + test IDATs; not part of `make test`)
#   make gate       the release gate: suite + docs gate + coverage in one
#                   8-core SLURM job, ~4.5 min (scripts/coverage.sh --sbatch)
#   make clean

CC      ?= cc
# The R oracle the golden tests compare against. Overridable because the
# binary is not called the same thing everywhere: on the lab HPC plain
# `Rscript` is a different R without a usable sesame, and Rscript-4.6.0 is
# the one to use. Exported so the tests/*.sh see it.
RSCRIPT ?= Rscript
export RSCRIPT
PREFIX  ?= /usr/local
CFLAGS  ?= -O2 -g
# _GNU_SOURCE makes POSIX/BSD functions (strdup, realpath, getline) visible under
# -std=c11 on glibc, where <string.h> etc. otherwise hide them. Chosen over
# _DEFAULT_SOURCE (unknown to the glibc 2.17 sysroot conda can use) and
# _XOPEN_SOURCE (which would suppress Darwin extensions); _GNU_SOURCE is honored
# by every glibc and is a no-op on macOS, where these are declared by default.
CFLAGS  += -D_GNU_SOURCE -std=c11 -Wall -Wextra -Wpedantic -Wshadow -Wconversion \
           -Wstrict-prototypes -Iinclude
# EXTRA_CFLAGS is appended to every compile (incl. mask.o) and EXTRA_LDFLAGS to
# every link, so `asan` can add sanitizers without clobbering the base flags a
# command-line CFLAGS= override would drop.
CFLAGS  += $(EXTRA_CFLAGS)
LDFLAGS += $(EXTRA_LDFLAGS)

# --- YAME: linked directly for reading .cm masks and for the shared asset
#     store. Both carry the same CHOP academic BSD-2 terms, which is what lets
#     us link it in-process. Built from the pinned submodule so the static lib
#     never goes stale. ---
YAME_DIR := YAME
YAME_LIB := $(YAME_DIR)/libyame.a
HTSLIB   := $(YAME_DIR)/htslib/libhts.a
YAME_INC := -I$(YAME_DIR)/src -I$(YAME_DIR)/htslib

# The whole link line -- libyame.a, libhts.a, and the pthread/z/m/curl set --
# comes from yame-config, generated by YAME's own build. Spelling it by hand is
# how two binaries end up resolving libcurl differently: a bare -lcurl picks
# whatever the linker finds first, which on a conda toolchain is the system one,
# and it then fails against conda's OpenSSL. The $$ defers the command
# substitution to the shell, so it runs after libyame.a (and thus yame-config)
# exists rather than when make parses this file.
YAME_LIBS := $$($(YAME_DIR)/yame-config --libs)

SRC     := src/util.c src/numerics.c src/idat.c src/index.c src/sigdf.c src/prep.c src/qc.c src/dml.c src/cnv.c src/cbs.c src/vcf.c src/region.c src/collapse.c src/liftover.c src/impute.c src/deidentify.c src/mask.c src/cgwrite.c src/describe.c src/cache.c
CLI_SRC := cli/main.c
OBJ     := $(SRC:.c=.o)
CLI_OBJ := $(CLI_SRC:.c=.o)
BIN     := sesame

.PHONY: test-betas-HM450 test-betas-EPIC test-betas-EPICv2 test-betas-MSA test-prep-HM450 test-prep-EPIC test-prep-EPICv2 test-prep-MSA test-pneg-HM450 test-pneg-EPIC test-pneg-EPICv2 test-pneg-MSA test-dyebiasL-HM450 test-dyebiasL-EPIC test-dyebiasL-EPICv2 test-dyebiasL-MSA test-gct-HM450 test-gct-EPIC test-gct-EPICv2 test-gct-MSA test-liftover-toEPIC test-liftover-toEPICv2 test-liftover-genome test-liftover-formats all asan docs test test-docs test-docs-check test-errors test-idat test-betas test-prep test-qmask test-poobah test-noob test-dyebiasL test-pneg test-collapse test-liftover test-impute test-gct test-neighbors test-batch test-qc test-dml test-cg test-describe test-cnv test-cbs test-vcf test-deidentify gate index cnv-normals registry yame-lib install fuzz fuzz-replay clean

all: $(BIN)

# src/registry.h is a projection of YAME's shared catalog (YAME/tools/registry),
# emitted by OUR generator against the catalog's lib.sh -- YAME dropped its
# --tool= flag in v1.50, and each tool now owns its emitter. It
# supplies the IDAT bead counts for platform auto-detection and the tag this
# build expects, quoted in the "asset missing" messages. Emission is offline.
registry:
	bash tools/make_registry.sh -o src/registry.h

# Install the binary into $(PREFIX)/bin (honours $(DESTDIR)). Used by the conda
# recipe; `make install PREFIX=/usr/local` for a manual install.
install: $(BIN)
	mkdir -p $(DESTDIR)$(PREFIX)/bin
	cp -f $(BIN) $(DESTDIR)$(PREFIX)/bin/$(BIN)
	chmod 755 $(DESTDIR)$(PREFIX)/bin/$(BIN)

# Incrementally (re)build libyame.a from the checked-out submodule.
yame-lib:
	$(MAKE) -C $(YAME_DIR) lib
$(YAME_LIB) $(HTSLIB) $(YAME_DIR)/yame-config: yame-lib

$(BIN): $(OBJ) $(CLI_OBJ) $(YAME_LIB) $(HTSLIB)
	$(CC) $(CFLAGS) $(LDFLAGS) -o $@ $(OBJ) $(CLI_OBJ) $(YAME_LIBS)

# main.c stamps in the YAME version it was built against, so `sesame version`
# names the yame that fills the store this binary reads -- and therefore the
# asset tags (InfiniumAnnotation, genomes) that come with it. It also includes
# YAME's yame_ui.h for the help styling, so it takes the same relaxed flags and
# include path as the other YAME-facing units. Needs libyame.a first, since
# yame-config is generated by YAME's build.
# yame-config is a REAL prerequisite, not order-only: it carries the version
# stamped into the binary, so when the submodule moves main.o must rebuild or
# `sesame version` keeps reporting the YAME it was first built against.
cli/main.o: cli/main.c include/sesame.h src/internal.h src/registry.h \
            $(YAME_DIR)/yame-config
	$(CC) -O2 -g -std=gnu11 -Wall -Iinclude $(YAME_INC) $(EXTRA_CFLAGS) \
	    -DSESAME_YAME_VERSION=\"$$($(YAME_DIR)/yame-config --version)\" \
	    -c -o $@ $<

# mask.c includes YAME headers (C99/GNU style); relax pedantic/conversion for it
# only, and give it the YAME include path.
src/mask.o: src/mask.c include/sesame.h src/internal.h | $(YAME_LIB)
	$(CC) -O2 -g -std=gnu11 -Wall -Iinclude $(YAME_INC) $(EXTRA_CFLAGS) -c -o $@ $<

# cgwrite.c also includes YAME headers; same relaxed rule as mask.o.
src/cgwrite.o: src/cgwrite.c include/sesame.h src/internal.h | $(YAME_LIB)
	$(CC) -O2 -g -std=gnu11 -Wall -Iinclude $(YAME_INC) $(EXTRA_CFLAGS) -c -o $@ $<

# liftover.c includes YAME headers for the genome lift (row_finder over the
# .cr, cdata read/write); same relaxed rule as cgwrite.o.
src/liftover.o: src/liftover.c include/sesame.h src/internal.h | $(YAME_LIB)
	$(CC) -O2 -g -std=gnu11 -Wall -Iinclude $(YAME_INC) $(EXTRA_CFLAGS) -c -o $@ $<

# attach.c also includes YAME headers; same relaxed rule as cgwrite.o.
src/describe.o: src/describe.c include/sesame.h src/internal.h | $(YAME_LIB)
	$(CC) -O2 -g -std=gnu11 -Wall -Iinclude $(YAME_INC) $(EXTRA_CFLAGS) -c -o $@ $<

# cache.c resolves the store root through YAME's shared asset layer (assets.h);
# same relaxed rule as the others.
src/cache.o: src/cache.c include/sesame.h src/internal.h src/registry.h | $(YAME_LIB)
	$(CC) -O2 -g -std=gnu11 -Wall -Iinclude $(YAME_INC) $(EXTRA_CFLAGS) -c -o $@ $<

%.o: %.c include/sesame.h src/internal.h src/registry.h
	$(CC) $(CFLAGS) -c -o $@ $<

asan: clean
	$(MAKE) EXTRA_CFLAGS="-fsanitize=address,undefined -fno-omit-frame-pointer" \
	        EXTRA_LDFLAGS="-fsanitize=address,undefined"

test: test-errors test-idat test-betas test-prep test-qmask test-poobah test-noob test-dyebiasL test-pneg test-collapse test-liftover test-impute test-gct test-neighbors test-batch test-qc test-dml test-cg test-describe test-cnv test-cbs test-vcf test-deidentify test-docs-check

# --- the slow drivers, split one target per platform -------------------------
#
# Each of these runs the R oracle once per platform, in series inside the one
# script, which made them the long pole: `make -j` schedules TARGETS, so a
# 4-platform driver is one job however many cores are free. Split, the longest
# job is one platform (~130 s at -O0) instead of four (~200 s), and it helps
# `make -j test` anywhere, not only where SLURM is.
#
# SESAME_ONLY is an ERE the driver matches each case against (see
# tests/run_*.sh); the aggregate name still runs all of them. `^EPIC ` has the
# space so it cannot also match EPICv2.

test-betas-HM450: $(BIN) pipeline_dump
	@SESAME_ONLY='^HM450 ' tests/run_betas.sh

test-betas-EPIC: $(BIN) pipeline_dump
	@SESAME_ONLY='^EPIC ' tests/run_betas.sh

test-betas-EPICv2: $(BIN) pipeline_dump
	@SESAME_ONLY='^EPICv2 ' tests/run_betas.sh

test-betas-MSA: $(BIN) pipeline_dump
	@SESAME_ONLY='^MSA ' tests/run_betas.sh

test-betas: test-betas-HM450 test-betas-EPIC test-betas-EPICv2 test-betas-MSA

test-prep-HM450: $(BIN) pipeline_dump
	@SESAME_ONLY='^HM450 ' tests/run_prep.sh

test-prep-EPIC: $(BIN) pipeline_dump
	@SESAME_ONLY='^EPIC ' tests/run_prep.sh

test-prep-EPICv2: $(BIN) pipeline_dump
	@SESAME_ONLY='^EPICv2 ' tests/run_prep.sh

test-prep-MSA: $(BIN) pipeline_dump
	@SESAME_ONLY='^MSA ' tests/run_prep.sh

test-prep: test-prep-HM450 test-prep-EPIC test-prep-EPICv2 test-prep-MSA

test-pneg-HM450: $(BIN) pipeline_dump
	@SESAME_ONLY='^HM450 ' tests/run_pneg.sh

test-pneg-EPIC: $(BIN) pipeline_dump
	@SESAME_ONLY='^EPIC ' tests/run_pneg.sh

test-pneg-EPICv2: $(BIN) pipeline_dump
	@SESAME_ONLY='^EPICv2 ' tests/run_pneg.sh

test-pneg-MSA: $(BIN) pipeline_dump
	@SESAME_ONLY='^MSA ' tests/run_pneg.sh

test-pneg: test-pneg-HM450 test-pneg-EPIC test-pneg-EPICv2 test-pneg-MSA

test-dyebiasL-HM450: $(BIN) pipeline_dump
	@SESAME_ONLY='^HM450 ' tests/run_dyebiasL.sh

test-dyebiasL-EPIC: $(BIN) pipeline_dump
	@SESAME_ONLY='^EPIC ' tests/run_dyebiasL.sh

test-dyebiasL-EPICv2: $(BIN) pipeline_dump
	@SESAME_ONLY='^EPICv2 ' tests/run_dyebiasL.sh

test-dyebiasL-MSA: $(BIN) pipeline_dump
	@SESAME_ONLY='^MSA ' tests/run_dyebiasL.sh

test-dyebiasL: test-dyebiasL-HM450 test-dyebiasL-EPIC test-dyebiasL-EPICv2 test-dyebiasL-MSA

test-gct-HM450: $(BIN)
	@SESAME_ONLY='^HM450 ' tests/run_gct.sh

test-gct-EPIC: $(BIN)
	@SESAME_ONLY='^EPIC ' tests/run_gct.sh

test-gct-EPICv2: $(BIN)
	@SESAME_ONLY='^EPICv2 ' tests/run_gct.sh

test-gct-MSA: $(BIN)
	@SESAME_ONLY='^MSA ' tests/run_gct.sh

test-gct: test-gct-HM450 test-gct-EPIC test-gct-EPICv2 test-gct-MSA

test-liftover-toEPIC: $(BIN) pipeline_dump
	@SESAME_ONLY=' EPIC$$' tests/run_liftover.sh

test-liftover-toEPICv2: $(BIN) pipeline_dump
	@SESAME_ONLY=' EPICv2$$' tests/run_liftover.sh

test-liftover-genome: $(BIN) pipeline_dump
	@SESAME_ONLY=' hg38$$' tests/run_liftover.sh

test-liftover-formats: $(BIN) pipeline_dump mu2cg
	@SESAME_ONLY='fmt|refusals' tests/run_liftover.sh

test-liftover: test-liftover-toEPIC test-liftover-toEPICv2 test-liftover-genome test-liftover-formats

# Negative tests: the error surface the golden ladder never touches. No R, no
# store, no IDATs -- so this one also runs in CI.
test-errors: $(BIN) mu2cg
	@tests/run_errors.sh

test-idat: $(BIN)
	@tests/run_golden.sh

# The docs gate, cheap half: every version, subcommand, flag and metric count
# the docs print, checked against THIS binary. No data, no network, under a
# second -- so it rides along in `make test` and in CI. It exists because a
# 2026-09 doc review ran the page verbatim and found nine printed lines that
# fail as printed; a deprecated flag and a wrong metric count are exactly what
# this catches.
test-docs-check: $(BIN)
	@python3 tests/docs_gate.py --consistency
	@python3 docs/build_help.py --check

# The documented-workflow gate: every docs/examples/*.sh run against this
# checkout's binary, in a sandbox, as a reader would. It needs a populated
# $$YAME_DATA_HOME and test IDATs at $$SESAME_TEST_IDATS, so it is NOT part of
# `make test` and never runs in CI or a conda build. On the HPC run it under
# sbatch (release SOP step 5). Skips cleanly when either input is absent.
# docs/index.html is prose around one generated part: the Reference tab, every
# subcommand's -h from THIS binary (docs/build_help.py). `make docs` writes it,
# `make test-docs-check` refuses a page behind the binary -- so it is a release
# step, run before the tag (the SOP says so).
docs: $(BIN)
	@python3 docs/build_help.py

test-docs: $(BIN)
	@python3 tests/docs_gate.py

test-qmask: $(BIN) pipeline_dump
	@tests/run_qmask.sh

test-poobah: $(BIN) pipeline_dump
	@tests/run_poobah.sh

# The B unit harness links only numerics.o (no other deps).
normexp_test: tests/normexp_test.c src/numerics.o include/sesame.h src/internal.h
	$(CC) $(CFLAGS) -Isrc -o $@ tests/normexp_test.c src/numerics.o -lm

# CBS unit harness: reads a bin-signal vector, prints segments. numerics.o + cbs.o.
cbs_test: tests/cbs_test.c src/cbs.o src/numerics.o include/sesame.h src/internal.h
	$(CC) $(CFLAGS) -Isrc -o $@ tests/cbs_test.c src/cbs.o src/numerics.o -lm

# Validation harness: full-precision library pipeline (links libsesame + YAME),
# so differential tests keep their bit-identical/ULP gates that the .cg product
# (float32) cannot carry.
pipeline_dump: tests/pipeline_dump.c $(OBJ) $(YAME_LIB) $(HTSLIB) include/sesame.h
	$(CC) $(CFLAGS) $(LDFLAGS) -o $@ tests/pipeline_dump.c $(OBJ) $(YAME_LIBS)

# M/U TSV -> format-3 .cg, for packing the CNV normal reference (export_cnvnormals.R).
mu2cg: tools/mu2cg.c $(OBJ) $(YAME_LIB) $(HTSLIB) include/sesame.h
	$(CC) $(CFLAGS) $(LDFLAGS) -o $@ tools/mu2cg.c $(OBJ) $(YAME_LIBS)

test-noob: $(BIN) normexp_test pipeline_dump
	@tests/run_noob.sh

test-collapse: $(BIN) pipeline_dump
	@tests/run_collapse.sh

test-impute: $(BIN)
	@tests/run_impute.sh

test-neighbors: $(BIN) pipeline_dump
	@tests/run_neighbors.sh

test-batch: $(BIN)
	@tests/run_batch.sh

test-qc: $(BIN)
	@tests/run_qc.sh

test-dml: $(BIN)
	@tests/run_dml.sh

test-cg: $(BIN) pipeline_dump
	@tests/run_cg.sh

test-describe: $(BIN) mu2cg
	@tests/run_describe.sh

test-cnv: $(BIN)
	@tests/run_cnv.sh

test-cbs: cbs_test
	@tests/run_cbs.sh

test-vcf: $(BIN)
	@tests/run_vcf.sh

test-deidentify: $(BIN)
	@tests/run_deidentify.sh

# The release gate in one command: suite + docs gate + coverage, one SLURM job
# per shard (scripts/coverage.sh --sbatch), and a stale badge fails it. Needs
# the R oracle (RSCRIPT=), the test IDATs and a populated $YAME_DATA_HOME.
gate: $(BIN)
	scripts/coverage.sh --sbatch --check

# Export ordering tables from sesameData (bootstrap; needs Rscript + sesame).
PLATFORMS := HM450 EPIC EPICv2 MSA
index:
	@for p in $(PLATFORMS); do \
	    $(RSCRIPT) tools/export_ordering.R $$p testdata/$$p.ordering.tsv.gz; \
	done

# Export the per-platform CNV normal references (format-3 .cg) from sesameData.
# This is how the <PLAT>.cnvnormals.cg shipped in the InfiniumAnnotation
# release (v8.2+) were made; `yame fetch` supplies them and `cnv` finds them in
# the store, so run this only to rebuild one. The panel is positional on the
# RELEASE ordering (the store copy), not testdata/ -- the testdata orderings
# are exported from R and can differ from the release (MSA: 8 extra probes).
# Genome-level genomeInfo is not here: it lives in zhou-lab/genomes (generate
# with tools/export_genomeinfo.R) and is pulled by `yame fetch genomes/<build>`.
# Needs Rscript and $YAME_DATA_HOME.
cnv-normals: mu2cg
	@for p in EPIC EPICv2 HM450 MSA; do \
	    mkdir -p data/$$p; \
	    $(RSCRIPT) tools/export_cnvnormals.R $$p \
	        $$YAME_DATA_HOME/$$p/$$p.ordering.tsv.gz \
	        data/$$p/$$p.cnvnormals.mu.tsv.gz && \
	    ./mu2cg data/$$p/$$p.cnvnormals.mu.tsv.gz \
	        data/$$p/$$p.cnvnormals.cg && \
	    rm -f data/$$p/$$p.cnvnormals.mu.tsv.gz; \
	done

# Real fuzzing. Needs a clang with libFuzzer (Linux CI); Apple clang has none.
fuzz:
	$(CC) -std=c11 -g -O1 -Iinclude -fsanitize=fuzzer,address,undefined \
	    fuzz/fuzz_idat.c src/idat.c src/util.c -lz -o fuzz_idat

# Corpus replayer under ASan/UBSan. Works everywhere, incl. Apple clang.
fuzz-replay:
	$(CC) -std=c11 -g -O1 -Iinclude -DSESAME_FUZZ_STANDALONE \
	    -fsanitize=address,undefined \
	    fuzz/fuzz_idat.c src/idat.c src/util.c -lz -o fuzz_replay

clean:
	rm -f $(OBJ) $(CLI_OBJ) $(BIN) normexp_test cbs_test pipeline_dump mu2cg fuzz_idat fuzz_replay
	rm -rf $(BIN).dSYM normexp_test.dSYM fuzz_replay.dSYM fuzz_idat.dSYM
