#!/bin/bash
## Generate src/registry.h from YAME's catalog.
##
## STAGED, NOT YET WIRED. The Makefile's `registry` target still calls
## YAME/tools/make_registry.sh --tool=sesame, which works up to and including
## YAME c8bc8e4 and is REMOVED in 85a437e (the registry migration's phase 4).
## This script replaces it, and must be wired in the same commit that bumps the
## submodule past c8bc8e4 -- a bumped submodule with a stale src/registry.h
## silently keeps the old `beads`, which is IDAT platform auto-detection.
##
## Written and verified against YAME 85a437e's tools/registry/lib.sh, whose
## whole surface is: rows_of files_of field key_source key_tag key_path url_of.
##
## The C edits that belong in the same commit:
##   - src/cache.c: quote each platform's own tag (SESAME_REGISTRY[].tag)
##     instead of one SESAME_DEFAULT_TAG, and print `yame fetch -y <dir>`
##     rather than `yame fetch <source>/<target>` (the old spelling is an alias
##     for one release only). Drop the `sesame betas --index` line: no such
##     subcommand.
##   - include/sesame.h: sesame_reg_t loses sums_sha256, gains tag.
##
## Usage: tools/make_registry.sh [-o src/registry.h]
set -euo pipefail

lib=${YAME_DIR:-YAME}/tools/registry/lib.sh
[ -r "$lib" ] || { echo "make_registry: no $lib (is the submodule checked out?)" >&2; exit 1; }
. "$lib"

out=${2:-/dev/stdout}
[ "${1:-}" = "-o" ] || out=/dev/stdout

PLATFORMS="EPIC EPICv2 HM450 MSA"
GENOMES="hg38 mm10 mm39"

## The IDAT bead count (nSNPsRead) per product, which is how preprocess
## auto-detects a platform from an IDAT alone. A sesame-only fact: it lived in
## YAME's catalog only while YAME emitted this header. Re-derive by reading any
## IDAT of that product -- `sesame idat-dump <file>` prints the count.
beads_of() {
  case $1 in
    EPIC)   echo 1051815 ;;
    EPICv2) echo 1105209 ;;
    HM450)  echo  622399 ;;
    MSA)    echo  384497 ;;
    *)      echo 0 ;;
  esac
}

tag_of_dir() {   ## the source@tag of a directory, one per directory by catalog rule
  local row; row=$(files_of "$1/*" | head -1)
  [ -n "$row" ] || { echo "make_registry: no catalog rows under $1/" >&2; exit 1; }
  key_tag "$(field "$row" key)"
}

{
  echo "/* registry.h -- GENERATED by tools/make_registry.sh. Do not edit."
  echo " *"
  echo " * Per platform: the IDAT bead count (auto-detection), the ordering file"
  echo " * name, and the catalog tag this build expects -- per platform, since the"
  echo " * catalog permits one platform to move tag while the rest stay."
  echo " */"
  echo "#ifndef SESAME_REGISTRY_H"
  echo "#define SESAME_REGISTRY_H"
  echo
  echo "typedef struct {"
  echo "    const char *platform;"
  echo "    int32_t     beads;      /* IDAT nSNPsRead; 0 = no auto-detect */"
  echo "    const char *ordering;   /* ordering table filename */"
  echo "    const char *tag;        /* catalog tag this build expects */"
  echo "} sesame_reg_t;"
  echo
  echo "static const sesame_reg_t SESAME_REGISTRY[] = {"
  for p in $PLATFORMS; do
    row=$(files_of "$p/$p.ordering.tsv.gz")
    printf '    { "%s", %s, "%s", "%s" },\n' \
      "$p" "$(beads_of "$p")" "$(basename "$(field "$row" store_path)")" \
      "$(key_tag "$(field "$row" key)")"
  done
  echo "    { NULL, 0, NULL, NULL }"
  echo "};"
  echo
  echo "typedef struct {"
  echo "    const char *genome;"
  echo "    const char *tag;"
  echo "} sesame_genome_reg_t;"
  echo
  echo "static const sesame_genome_reg_t SESAME_GENOMES[] = {"
  for g in $GENOMES; do
    printf '    { "%s", "%s" },\n' "$g" "$(tag_of_dir "$g")"
  done
  echo "    { NULL, NULL }"
  echo "};"
  echo
  echo "/* The files this build reads, for the record. A directory glob is that"
  echo " * directory's own files (YAME c8bc8e4 onward); cpg_nocontig.cr is the"
  echo " * suite's row space, which sesame does not open. */"
  for p in $PLATFORMS; do
    files_of "$p/*" | while IFS= read -r r; do
      printf '/*   %-36s %s */\n' "$(field "$r" store_path)" "$(field "$r" sha256 | cut -c1-12)"
    done
  done
  for g in $GENOMES; do
    files_of "$g/*" | grep -v 'cpg_nocontig\.cr' | while IFS= read -r r; do
      printf '/*   %-36s %s */\n' "$(field "$r" store_path)" "$(field "$r" sha256 | cut -c1-12)"
    done
  done
  echo
  echo "#endif"
} > "$out"
