#!/usr/bin/env python3
"""Render every subcommand's `-h` into the Reference tab of docs/index.html.

The help text is what the binary prints, never pasted: this runs
`./sesame <sub> -h` for every subcommand the `sesame help` banner advertises
and fills the marker pair on the Reference tab -- one card per banner section
(Preprocessing, Analysis, Inspect / convert, Other), a folded entry per
subcommand with the id `ref-<sub>`, so an example's highlighted `sesame <sub>`
links to it and opens it. Order and grouping are the banner's own.

The binary runs under a FIXED environment (HOME=/home/user, no store or XDG
variables), because the banner and `version` print the resolved store path
and the page must not depend on whose machine built it.

    docs/build_help.py            rewrite docs/index.html in place
    docs/build_help.py --check    exit 1 if the page is behind the binary

`make docs` runs it; `make test-docs-check` runs --check -- so the page can
never show help the binary does not print. Same shape as methscope's.
"""
import html, os, re, subprocess, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PAGE = os.path.join(ROOT, "docs", "index.html")
BIN = os.environ.get("SESAME_BIN") or os.path.join(ROOT, "sesame")
BEGIN = "<!-- help:begin (generated by docs/build_help.py from `sesame <sub> -h`) -->"
END = "<!-- help:end -->"
ENV = {"HOME": "/home/user", "PATH": os.environ.get("PATH", ""), "LANG": "C"}
SKIP = {"help"}                       # its -h is the banner itself

def run(*args):
    p = subprocess.run([BIN, *args], capture_output=True, text=True, env=ENV)
    return (p.stdout + p.stderr).rstrip()

def banner_sections():
    """[(section, [(name, desc), ...]), ...] as `sesame help` groups them: a
    section is an unindented line, an entry a 4-space-indented `name  desc`."""
    out, cur = [], None
    for line in run("help").splitlines():
        if not line.strip(): continue
        if not line.startswith(" "):
            cur = (line.strip(), []); out.append(cur); continue
        m = re.match(r"^\s{4}(\S+)\s+(.+)$", line)   # one space when the name fills its column (attach-probe)
        if m and cur and cur[0] not in ("Usage", "Data") and m.group(1) not in SKIP:
            cur[1].append((m.group(1), m.group(2).strip()))
    return [(h, c) for h, c in out if c]

def entry(name, desc):
    body = run(name, "-h")
    return ('  <details class="ref" id="ref-%s">\n    <summary><code class="inl">sesame %s</code>'
            ' <span class="m">— %s</span></summary>\n'
            '    <pre class="help"><code>%s</code></pre>\n  </details>'
            % (name, name, html.escape(desc, quote=False), html.escape(body, quote=False)))

def build():
    out, n = [BEGIN], 0
    for heading, cmds in banner_sections():
        out.append('<section class="card">\n  <h2>%s</h2>' % html.escape(heading, quote=False))
        for name, desc in cmds:
            out.append(entry(name, desc)); n += 1
        out.append('</section>')
    out.append(END)
    return "\n".join(out), n

def main():
    page = open(PAGE, encoding="utf-8").read()
    i, j = page.find(BEGIN), page.find(END)
    if i < 0 or j < 0: sys.exit("build_help.py: markers not found in docs/index.html")
    block, n = build()
    new = page[:i] + block + page[j + len(END):]
    if "--check" in sys.argv:
        if new != page: sys.exit("docs/index.html Reference tab is behind the binary's -h: run `make docs`")
        print("  ok   Reference tab is current (%d subcommands)" % n); return
    if new != page:
        open(PAGE, "w", encoding="utf-8").write(new); print("rendered %d subcommand references into docs/index.html" % n)
    else:
        print("reference unchanged")

if __name__ == "__main__": main()
