/* registry.h -- GENERATED by tools/make_registry.sh. Do not edit.
 *
 * Per platform: the IDAT bead count (auto-detection), the ordering file
 * name, and the catalog tag this build expects -- per platform, since the
 * catalog permits one platform to move tag while the rest stay.
 */
#ifndef SESAME_REGISTRY_H
#define SESAME_REGISTRY_H

typedef struct {
    const char *platform;
    int32_t     beads;      /* IDAT nSNPsRead; 0 = no auto-detect */
    const char *ordering;   /* ordering table filename */
    const char *tag;        /* catalog tag this build expects */
} sesame_reg_t;

static const sesame_reg_t SESAME_REGISTRY[] = {
    { "EPIC", 1051815, "EPIC.ordering.tsv.gz", "v8.1" },
    { "EPICv2", 1105209, "EPICv2.ordering.tsv.gz", "v8.1" },
    { "HM450", 622399, "HM450.ordering.tsv.gz", "v8.1" },
    { "MSA", 384497, "MSA.ordering.tsv.gz", "v8.1" },
    { NULL, 0, NULL, NULL }
};

typedef struct {
    const char *genome;
    const char *tag;
} sesame_genome_reg_t;

static const sesame_genome_reg_t SESAME_GENOMES[] = {
    { "hg38", "v4" },
    { "mm10", "v4" },
    { "mm39", "v4" },
    { NULL, NULL }
};

/* The files this build reads, for the record. A directory glob is that
 * directory's own files (YAME c8bc8e4 onward); cpg_nocontig.cr is the
 * suite's row space, which sesame does not open. */
/*   EPIC/EPIC.ordering.tsv.gz            a55f9587ec02 */
/*   EPIC/EPIC.hg38.coord.tsv.gz          08904e7dd06f */
/*   EPIC/EPIC.hg38.snp.tsv.gz            f4310e531401 */
/*   EPIC/EPIC.typeI_ext.tsv.gz           e2ecbe9c7bc7 */
/*   EPIC/EPIC.hg38.mask.cm               28a4d03b714f */
/*   EPIC/EPIC.hg38.mask.cm.idx           bf0ba8148596 */
/*   EPICv2/EPICv2.ordering.tsv.gz        52f8c45dc9d9 */
/*   EPICv2/EPICv2.hg38.coord.tsv.gz      6c2213eff46a */
/*   EPICv2/EPICv2.hg38.snp.tsv.gz        e4cef2b827ab */
/*   EPICv2/EPICv2.typeI_ext.tsv.gz       4872dab7ec1e */
/*   EPICv2/EPICv2.hg38.mask.cm           7463ce67bb26 */
/*   EPICv2/EPICv2.hg38.mask.cm.idx       00b94541b3c8 */
/*   HM450/HM450.ordering.tsv.gz          e5106a34e970 */
/*   HM450/HM450.hg38.coord.tsv.gz        bedd968a41a2 */
/*   HM450/HM450.hg38.snp.tsv.gz          3ad6d0226b9d */
/*   HM450/HM450.typeI_ext.tsv.gz         dd223d6672d5 */
/*   HM450/HM450.hg38.mask.cm             adebc62a6e6c */
/*   HM450/HM450.hg38.mask.cm.idx         27dff6eb3032 */
/*   MSA/MSA.ordering.tsv.gz              f89fa5ff525b */
/*   MSA/MSA.hg38.coord.tsv.gz            08f4c9a307cb */
/*   MSA/MSA.hg38.snp.tsv.gz              e0521bdf0598 */
/*   MSA/MSA.typeI_ext.tsv.gz             b261dd9f9569 */
/*   MSA/MSA.hg38.mask.cm                 928e9f782e7d */
/*   MSA/MSA.hg38.mask.cm.idx             b6c0d7a80c3e */
/*   hg38/seqinfo.tsv.gz                  fb0451cc3a14 */
/*   hg38/gaps.tsv.gz                     0585abdbf802 */
/*   hg38/cytoband.tsv.gz                 a49a0cf26294 */
/*   hg38/genes.bed.gz                    0ec51c895e05 */
/*   hg38/genes.bed.gz.tbi                fa4064aed5e8 */
/*   mm10/seqinfo.tsv.gz                  ed48effa987d */
/*   mm10/gaps.tsv.gz                     91f3ec9b0856 */
/*   mm10/cytoband.tsv.gz                 a7bb429fb76b */
/*   mm10/genes.bed.gz                    0e4497a94a88 */
/*   mm10/genes.bed.gz.tbi                5f6b4acadd9e */
/*   mm39/seqinfo.tsv.gz                  bdcee6698a3d */
/*   mm39/gaps.tsv.gz                     002c5aa5e3ef */
/*   mm39/cytoband.tsv.gz                 20f66bce778c */
/*   mm39/genes.bed.gz                    ce6c63a5ab35 */
/*   mm39/genes.bed.gz.tbi                6002f81994af */

#endif
